import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Schema as MongooseSchema } from 'mongoose';

export type ActivityDocument = Activity & Document;

@Schema({ timestamps: true })
export class Activity {
  // ⭐ CHANGED: projectId is now optional (required: false)
  @Prop({ type: MongooseSchema.Types.ObjectId, ref: 'Project', required: false, index: true })
  projectId?: MongooseSchema.Types.ObjectId;

  @Prop({ type: MongooseSchema.Types.ObjectId, ref: 'User', required: true })
  userId: MongooseSchema.Types.ObjectId;

  @Prop({
    type: String,
    required: true,
    enum: [
      'task_created',
      'task_completed',
      'task_deleted',
      'file_uploaded',
      'file_deleted',
      'message_sent',
      'payment_sent',
      'email_exchanged',
      'member_added',
      'member_removed',
      'announcement_created',
      'project_shipped',
      'comment_added'
    ]
  })
  action: string;

  @Prop({ type: MongooseSchema.Types.Mixed, default: {} })
  details: Record<string, any>;

  @Prop({
    type: {
      taskTitle: { type: String, required: false },
      fileName: { type: String, required: false },
      fileSize: { type: Number, required: false },
      recipientName: { type: String, required: false },
      amount: { type: Number, required: false },
      messagePreview: { type: String, required: false }
    },
    required: false,
    _id: false
  })
  metadata?: {
    taskTitle?: string;
    fileName?: string;
    fileSize?: number;
    recipientName?: string;
    amount?: number;
    messagePreview?: string;
  };

  // ⭐ ADDED: Explicit timestamps (auto-generated by { timestamps: true })
  createdAt?: Date;
  updatedAt?: Date;
}

export const ActivitySchema = SchemaFactory.createForClass(Activity);

// Compound indexes for fast queries
ActivitySchema.index({ projectId: 1, createdAt: -1 });
ActivitySchema.index({ userId: 1, createdAt: -1 });
